name: neon_academy_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  audioplayers: ^6.1.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  image_picker: ^1.1.2
  intl: ^0.20.1
  flutter_colorpicker: ^1.1.0
  flutter_local_notifications: ^18.0.1
  lottie: ^3.1.3
  onesignal_flutter: ^5.2.9
  google_mobile_ads: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.1.4
  mobx_codegen: ^2.7.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/
