name: neon_academy_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  audioplayers: ^6.1.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  image_picker: ^1.1.2
  intl: ^0.20.1
  flutter_colorpicker: ^1.1.0
  flutter_local_notifications: ^18.0.1
  lottie: ^3.1.3
  http: ^1.2.2
  dio: ^5.7.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  onesignal_flutter: ^5.2.9
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  get_it: ^8.0.3
  flutter_riverpod: ^2.6.1
  firebase_storage: ^12.4.0
  uuid: ^4.5.1
  path_provider: ^2.1.5
  firebase_remote_config: ^5.3.0
  firebase_crashlytics: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.1.4
  mobx_codegen: ^2.3.0
  hive_generator: ^2.0.1
  

flutter:
  uses-material-design: true
  assets:
    - assets/
