// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5HYBL8umYJolvwVka5oUwxgNkPHGw_1s',
    appId: '1:929610038844:web:e5ca5b21bc356f389acd39',
    messagingSenderId: '929610038844',
    projectId: 'neonacademyworkspace',
    authDomain: 'neonacademyworkspace.firebaseapp.com',
    storageBucket: 'neonacademyworkspace.firebasestorage.app',
    measurementId: 'G-48EZHQKSCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtvy372pZVtuW399IkhzGAVCf-fXLD-dE',
    appId: '1:929610038844:android:8440f54778a345dd9acd39',
    messagingSenderId: '929610038844',
    projectId: 'neonacademyworkspace',
    storageBucket: 'neonacademyworkspace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC69GWpJpzUveguy6lJ8XDmk8GM-9fwW3Y',
    appId: '1:929610038844:ios:408879369f4e2be19acd39',
    messagingSenderId: '929610038844',
    projectId: 'neonacademyworkspace',
    storageBucket: 'neonacademyworkspace.firebasestorage.app',
    iosBundleId: 'com.example.neonAcademyWorkspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC69GWpJpzUveguy6lJ8XDmk8GM-9fwW3Y',
    appId: '1:929610038844:ios:408879369f4e2be19acd39',
    messagingSenderId: '929610038844',
    projectId: 'neonacademyworkspace',
    storageBucket: 'neonacademyworkspace.firebasestorage.app',
    iosBundleId: 'com.example.neonAcademyWorkspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5HYBL8umYJolvwVka5oUwxgNkPHGw_1s',
    appId: '1:929610038844:web:c8a189cdc68ba9969acd39',
    messagingSenderId: '929610038844',
    projectId: 'neonacademyworkspace',
    authDomain: 'neonacademyworkspace.firebaseapp.com',
    storageBucket: 'neonacademyworkspace.firebasestorage.app',
    measurementId: 'G-5RP05B6EMP',
  );
}
